### ISSUE TITLE
Seek media item by time amount without pausing

### ISSUE THREAD

**Issue by YuriHeupa** [brianwernick/PlaylistCore#18]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
###### Include the following:
- PlaylistCore version: `1.1.1`
- Device OS version: `5.0.2`
- Devide Manufacturer: `HTC`
- Device Name: `One X`

I'm developing a feature that user can seek media item position by x amount of time in a button click. Let's say the amount is 15 seconds, so I need to do the following:

``` java
int seekAmount = 15000;
playlistManager.invokeSeekStarted();
playlistManager.invokeSeekEnded((int) mediaProgress.getPosition() + seekAmount);
```

But this pauses the audio for a while, and I want to seek on the fly. If I just call `invokeSeekEnded()` without the the `invokeSeekStarted()` playbackState stucks in SEEKING state. 
###### Expected Result

I expected just call invokeSeekEnded without seek started event, because this is redundant in this case. Or to have a custom method to seek without pausing the audio, with will just move the playback position without changing playbackState.

**Comment by brianwernick** [comment]
Any time you perform a seek we update the playbackState to `SEEKING` because that is the state.  The issue is that the playback state isn't being saved when a seek happens when paused, or if you seek without calling `invokeSeekStarted()`.

In the meantime you can just override the state functionality for seeking in the [PlaylistService#L582](https://github.com/brianwernick/PlaylistCore/blob/master/library/src/main/java/com/devbrackets/android/playlistcore/service/PlaylistServiceCore.java#L582) with

``` java
    @Override
    protected void performSeekEnded(int position) {
        performSeek(position, false);
    }
```
