### ISSUE TITLE
Help: getNotificationClickPendingIntent() method  pass value to activity

### ISSUE THREAD

**Issue by jyh149129** [brianwernick/PlaylistCore#41]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - PlaylistCore version: `1.1.3`
 - Device OS version: `5.0`
 - Devide Manufacturer: `xiaomi`
 my ccode :
```java
   @NonNull
    @Override
    protected PendingIntent getNotificationClickPendingIntent() {
        if(currentPlaylistItem!= null) {
            intent = new Intent(this, AudioStationPlay_JcPlayerActivity.class);
           // i want pass  param to AudioStationPlay_JcPlayerActivity
            intent.putExtra("cid", currentPlaylistItem.getPlaylistId()); // vlaue 4
            intent.putExtra("pid", 1);
            return PendingIntent.getActivity(this, FOREGROUND_REQUEST_CODE, intent, PendingIntent.FLAG_UPDATE_CURRENT);
        } else
            return PendingIntent.getActivity(getApplicationContext(), FOREGROUND_REQUEST_CODE, new Intent(getApplicationContext(), AppStart.class), PendingIntent.FLAG_UPDATE_CURRENT);
    }
```
In AudioStationPlay_JcPlayerActivity i can't get the "cid" and "pid" value(both log out value "0")  why?

sorry my bad englisth...

**Comment by Gounlaf** [comment]
Hi @jyh149129,

Your problem is not related to PlaylistCore itself.

Take a look here:
* https://stackoverflow.com/questions/18037991/pendingintent-does-not-send-intent-extras
* https://stackoverflow.com/questions/3168484/pendingintent-works-correctly-for-the-first-notification-but-incorrectly-for-the

You have set flag `PendingIntent.FLAG_UPDATE_CURRENT`: a side effect is that your extra data are not updated!
More answers and explanations in the two links above

**Comment by jyh149129** [comment]
ok,thanks.

**Comment by jyh149129** [comment]
.....
intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP | Intent.FLAG_ACTIVITY_SINGLE_TOP | Intent.FLAG_ACTIVITY_NEW_TASK);
intent.setAction(Long.toString(System.currentTimeMillis())); //importent
.....
all right is fine.Thanks so much
