### ISSUE TITLE
How to play music when kill app

### ISSUE THREAD

**Issue by binbin269x** [brianwernick/PlaylistCore#42]
When i kill app, service kill. i want kill app then service play music continue play.
i setup
        setupForeground();
 and 
    public int getServiceContinuationMethod() {
        return START_STICKY;
    }

but not working.
plz help me

**Comment by brianwernick** [comment]
Sorry for the late reply; I thought that this used to work but no longer so I'll add it to my list of things to fix and verify for the upcoming 2.0 release.

**Comment by brianwernick** [comment]
So the root cause of this is the call to `onDestroy()` from `onTaskRemoved` (see [PlaylistServiceCore#onTaskRemoved(Intent)](https://github.com/brianwernick/PlaylistCore/blob/master/library/src/main/java/com/devbrackets/android/playlistcore/service/PlaylistServiceCore.java#L330)). So as a fix for the current library (1.x) you can override that method and perform a no-op (this is the default of services)

**Comment by brianwernick** [comment]
Fixed on the 2.0 branch so I'm going to close this
