### ISSUE TITLE
How to add a single audio and get a playlist

### ISSUE THREAD

**Issue by cmz-one** [brianwernick/PlaylistCore#70]
playlistManager.setParameters() can add audio list，
But if i just add a audio to the playlist, What should I do？

And，How do I get a playlist？

**Comment by brianwernick** [comment]
Are you extending [ListPlaylistManager](https://github.com/brianwernick/PlaylistCore/blob/master/library/src/main/kotlin/com/devbrackets/android/playlistcore/manager/ListPlaylistManager.kt)? If so you won't be able to modify the list as it's a `List` instead of a `MutableList`. You'll need to extend the [BasePlaylistManager](https://github.com/brianwernick/PlaylistCore/blob/master/library/src/main/kotlin/com/devbrackets/android/playlistcore/manager/BasePlaylistManager.kt) instead with similar functionality to the `ListPlaylistManager` but with a mutable list (you could just copy that class and update the `items` to be a `MutableList`).

**Comment by cmz-one** [comment]
Thanks for the answer.
I extend the BasePlaylistManager,How to move it out of the list after audio playback is finished？

**Comment by brianwernick** [comment]
What are you trying to do that would require you to remove an item from the playlist? If you are trying to do something like a streaming service where you can't go back to the previous item then you'll want to use an `Iterable` or `Enumerable` instead of a `MutableList` in your PlaylistManager class.

**Comment by cmz-one** [comment]
When I finish playing an audio, I need to move it out of the list.

**Comment by cmz-one** [comment]
How to listen the event for the audio to finish complete

**Comment by brianwernick** [comment]
See the documentation and demo app
